#!/bin/bash

pgc=$(pdfinfo $1 | grep Pages: | tr -d -c 0-9)
for i in $(seq $pgc); do
  inkscape --pdf-poppler --pdf-page=$i --export-plain-svg --export-filename=- $1 | svgo -i - -o svg/${1%.*}-$i.svg
done
echo $pgc pages exportées